name = "mou-best"

routes = [
    { pattern = "mou.best", custom_domain = true },
    { pattern = "www.mou.best", custom_domain = true },
]

# KV Namespaces
[[kv_namespaces]]
binding = "CACHE"
id = "1be06b521598425ca7b6402fde42232d"

[[d1_databases]]
binding = "DB"
database_name = "mou-best-db"
database_id = "ff404be0-27ca-4f7a-8420-80712feab329"
